### ISSUE TITLE
Activity toolbar widget hide leaves canvas ghosts

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugargame#13]
When the activity toolbar is shown, and the description widget shown, then hidden, an area of canvas corresponding to the widget is not updated.

Reported in https://github.com/sugarlabs/hittheballs-activity/pull/10.

Also affects the Sugargame test activity.

(Some testing was done.  PygameCanvas is a Gtk.EventBox containing a Gtk.Socket.  A _visibility-notify-event_ can be connected to the Gtk.Socket.  The Pygame event loop can also return VIDEOEXPOSE events.  Calling pygame.display.update() in response to VIDEOEXPOSE improves the outcome where the toolbar is drawn in response to clicks, but not when the toolbar and description widgets are drawn in response to mouse-over actions.)

**Comment by vaibhav-sangwan** [comment]
@quozl, I was trying to replicate this issue in an activity that doesn't use sugargame. When activity toolbar buttons are clicked on or hovered over, a configure-event signal is emitted. This event is then handled by the event handlers connected to the object.

However, the problem arises because of canvas' size allocation. As can be seen from the following video, the size allocation of the canvas when configure-event occurs is different from the current allocation. The integer values in the tuples represent x, y, width and height respectively. The parameters sent to configure-event handler consist of old canvas size, stopping the canvas from expanding back. In addition to the ghost canvas issue, this also causes the canvas to not be shrinked down when the user clicks on activity toolbar button.

Adding delay to the configure-event handler `_resize_cb` in _events.py_ using `GLib.timeout_add_seconds()` solves both of these issues but comes with the downside of late resizing.


https://github.com/sugarlabs/sugargame/assets/94783049/d04cbfba-a68d-420f-9e3a-3b1faba4609b

**Comment by quozl** [comment]
Thanks.  When adding a delay changes behaviour, most likely cause is a race condition.  I see a pull request referenced.  Is this issue fixed now?

**Comment by vaibhav-sangwan** [comment]
Yes, the issue has been fixed.

**Comment by quozl** [comment]
Thanks.
